### ISSUE TITLE
wtf is this

### ISSUE THREAD

**Issue by Skillnoob** [Eralp232/BozeClient-Web#2]
you got the css and index.html + some other random files which you can download straight away how is this the source

**Comment by eralp232** [comment]
You can skid it to your shitty webpage, if you want.

**Comment by Skillnoob** [comment]
> You can skid it to your shitty webpage, if you want.

The boze website is shit why would i want to skid it

**Comment by eralp232** [comment]
I didn't create the repo just for you, maybe someone can use it

**Comment by Skillnoob** [comment]
> I didn't create the repo just for you, maybe someone can use it

"You can skid"
